language: node_js
node_js:
  - "12"

before_script:
  - npm run setup
  - npm run build-only

script:
  - npm run test

after_success:
  - npm run typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true