const FB_PAGE_ID = process.env.FB_PAGE_ID
const FB_PAGE_TOKEN = process.env.FB_PAGE_TOKEN
const FB_VERIFY_TOKEN = process.env.FB_VERIFY_TOKEN
const DARKSKY_KEY = process.env.DARKSKY_KEY
const NEWSAPI_KEY = process.env.NEWSAPI_KEY
const UNSPLASH_ID = process.env.UNSPLASH_ID
const UNSPLASH_SECRET = process.env.UNSPLASH_SECRET
const TWITTER_CONSUMER_KEY = process.env.TWITTER_CONSUMER_KEY
const TWITTER_CONSUMER_SECRET = process.env.TWITTER_CONSUMER_SECRET
const TWITTER_ACCESS_TOKEN_KEY = process.env.TWITTER_ACCESS_TOKEN_KEY
const TWITTER_ACCESS_TOKEN_SECRET = process.env.TWITTER_ACCESS_TOKEN_SECRET
const GIT_ID = process.env.GIT_ID
const GIT_PW = process.env.GIT_PW
const ADMIN_ID = '1200016940105472'
const ZAMZAR_APIKEY = process.env.ZAMZAR_APIKEY
const GOOGLE_APPLICATION_CREDENTIALS = process.env.GOOGLE_APPLICATION_CREDENTIALS
const GOOGLE_PROJECT_ID = 'elevated-honor-135514'
const TELEGRAM_TOKEN = process.env.TELEGRAM_TOKEN
const PORT = process.env.PORT || 8445
const PGURI = process.env.PGURI
const MONGO_DB_URI = process.env.MONGO_DB_URI
const CACHE_DURATION = process.env.CACHE_DURATION
const NASA_APIKEY = process.env.NASA_APIKEY
export {
	FB_PAGE_ID,
	FB_VERIFY_TOKEN,
	FB_PAGE_TOKEN,
	DARKSKY_KEY,
	NEWSAPI_KEY,
	UNSPLASH_ID,
	UNSPLASH_SECRET,

	TWITTER_CONSUMER_KEY,
	TWITTER_CONSUMER_SECRET,
	TWITTER_ACCESS_TOKEN_KEY,
	TWITTER_ACCESS_TOKEN_SECRET,

	GIT_ID,
	GIT_PW,
	ADMIN_ID,
	ZAMZAR_APIKEY,
	GOOGLE_APPLICATION_CREDENTIALS,
	GOOGLE_PROJECT_ID,
	TELEGRAM_TOKEN,
	PORT,
	PGURI,
	MONGO_DB_URI,
	CACHE_DURATION,
	NASA_APIKEY
}
